# Dealing With Categorical Values

## Importing Libraries

In [18]:
import pandas as pd
import numpy as np

## Importing Dataset

In [19]:
dataset = pd.read_csv("Salary_Dataset.csv")

In [20]:
dataset.head(40)

      country    Salary  YearsExperience Purchased
0       Dubai   39343.0              1.1        No
1      Canada   46205.0              1.3       Yes
2      Canada   37731.0              1.5        No
3      Canada   43525.0              2.0        No
4         USA   39891.0              2.2        No
5       Dubai   56642.0              2.9        No
6      Canada   60150.0              3.0       Yes
7   Australia   54445.0              3.2        No
8       Dubai   64445.0              3.2       Yes
9       Dubai   57189.0              3.7        No
10      Dubai   63218.0              3.9       Yes
11        USA   55794.0              4.0        No
12      Dubai   56957.0              4.0       Yes
13     Canada   57081.0              4.1        No
14  Australia   61111.0              4.5        No
15        USA   67938.0              4.9        No
16        USA   66029.0              5.1        No
17     Canada   83088.0              5.3        No
18  Australia   81363.0              5.9       Yes
19     Canada   93940.0              6.0        No
20     Canada   91738.0              6.8        No
21  Australia   98273.0              7.1        No
22  Australia  101302.0              7.9        No
23  Australia  113812.0              8.2       Yes
24      Dubai  109431.0              8.7        No
25  Australia  105582.0              9.0       Yes
26      Dubai  116969.0              9.5        No
27        USA  112635.0              9.6       Yes
28        USA  122391.0             10.3        No
29     Canada  121872.0             10.5       Yes

# Lets perform Encoding

## Applying One-Hot Encoding

<h3> First Do it with pandas </h3>

In [21]:
# Get dummies with pandas in any variable
country_dummies = pd.get_dummies(dataset['country'])
country_dummies.head(10)

   Australia  Canada  Dubai    USA
0      False   False   True  False
1      False    True  False  False
2      False    True  False  False
3      False    True  False  False
4      False   False  False   True
5      False   False   True  False
6      False    True  False  False
7       True   False  False  False
8      False   False   True  False
9      False   False   True  False

In [22]:
# concatenate the dataframes into original dataframes.
df = pd.concat([dataset, country_dummies], axis=1)
df.head(40)

,country,Salary,YearsExperience,Purchased,Australia,Canada,Dubai,USA
0,Dubai,39343.0,1.1,No,False,False,True,False
1,Canada,46205.0,1.3,Yes,False,True,False,False
2,Canada,37731.0,1.5,No,False,True,False,False
3,Canada,43525.0,2.0,No,False,True,False,False
4,USA,39891.0,2.2,No,False,False,False,True
5,Dubai,56642.0,2.9,No,False,False,True,False
6,Canada,60150.0,3.0,Yes,False,True,False,False
7,Australia,54445.0,3.2,No,True,False,False,False
8,Dubai,64445.0,3.2,Yes,False,False,True,False
9,Dubai,57189.0,3.7,No,False,False,True,False
10,Dubai,63218.0,3.9,Yes,False,False,True,False
11,USA,55794.0,4.0,No,False,False,False,True
12,Dubai,56957.0,4.0,Yes,False,False,True,False
13,Canada,57081.0,4.1,No,False,True,False,False
14,Australia,61111.0,4.5,No,True,False,False,False
15,USA,67938.0,4.9,No,False,False,False,True
16,USA,66029.0,5.1,No,False,False,False,True
17,Canada,83088.0,5.3,No,False,True,False,False
18,Australia,81363.0,5.9,Yes,True,False,False,False
19,Canada,93940.0,6.0,No,False,True,False,False
20,Canada,91738.0,6.8,No,False,True,False,False
21,Australia,98273.0,7.1,No,True,False,False,False
22,Australia,101302.0,7.9,No,True,False,False,False
23,Australia,113812.0,8.2,Yes,True,False,False,False
24,Dubai,109431.0,8.7,No,False,False,True,False
25,Australia,105582.0,9.0,Yes,True,False,False,False
26,Dubai,116969.0,9.5,No,False,False,True,False
27,USA,112635.0,9.6,Yes,False,False,False,True
28,USA,122391.0,10.3,No,False,False,False,True
29,Canada,121872.0,10.5,Yes,False,True,False,False

In [23]:
# Drop the country column and rearrange the index of column.
df.drop('country', axis=1, inplace=True)
df.head(40)

      Salary  YearsExperience Purchased  Australia  Canada  Dubai    USA
0    39343.0              1.1        No      False   False   True  False
1    46205.0              1.3       Yes      False    True  False  False
2    37731.0              1.5        No      False    True  False  False
3    43525.0              2.0        No      False    True  False  False
4    39891.0              2.2        No      False   False  False   True
5    56642.0              2.9        No      False   False   True  False
6    60150.0              3.0       Yes      False    True  False  False
7    54445.0              3.2        No       True   False  False  False
8    64445.0              3.2       Yes      False   False   True  False
9    57189.0              3.7        No      False   False   True  False
10   63218.0              3.9       Yes      False   False   True  False
11   55794.0              4.0        No      False   False  False   True
12   56957.0              4.0       Yes      False   False   True  False
13   57081.0              4.1        No      False    True  False  False
14   61111.0              4.5        No       True   False  False  False
15   67938.0              4.9        No      False   False  False   True
16   66029.0              5.1        No      False   False  False   True
17   83088.0              5.3        No      False    True  False  False
18   81363.0              5.9       Yes       True   False  False  False
19   93940.0              6.0        No      False    True  False  False
20   91738.0              6.8        No      False    True  False  False
21   98273.0              7.1        No       True   False  False  False
22  101302.0              7.9        No       True   False  False  False
23  113812.0              8.2       Yes       True   False  False  False
24  109431.0              8.7        No      False   False   True  False
25  105582.0              9.0       Yes       True   False  False  False
26  116969.0              9.5        No      False   False   True  False
27  112635.0              9.6       Yes      False   False  False   True
28  122391.0             10.3        No      False   False  False   True
29  121872.0             10.5       Yes      False    True  False  False

In [28]:
df_1=df[['Australia','Canada','Dubai','USA','Salary','YearsExperience','Purchased']]
df_1.head(40)

    Australia  Canada  Dubai    USA    Salary  YearsExperience Purchased
0       False   False   True  False   39343.0              1.1        No
1       False    True  False  False   46205.0              1.3       Yes
2       False    True  False  False   37731.0              1.5        No
3       False    True  False  False   43525.0              2.0        No
4       False   False  False   True   39891.0              2.2        No
5       False   False   True  False   56642.0              2.9        No
6       False    True  False  False   60150.0              3.0       Yes
7        True   False  False  False   54445.0              3.2        No
8       False   False   True  False   64445.0              3.2       Yes
9       False   False   True  False   57189.0              3.7        No
10      False   False   True  False   63218.0              3.9       Yes
11      False   False  False   True   55794.0              4.0        No
12      False   False   True  False   56957.0              4.0       Yes
13      False    True  False  False   57081.0              4.1        No
14       True   False  False  False   61111.0              4.5        No
15      False   False  False   True   67938.0              4.9        No
16      False   False  False   True   66029.0              5.1        No
17      False    True  False  False   83088.0              5.3        No
18       True   False  False  False   81363.0              5.9       Yes
19      False    True  False  False   93940.0              6.0        No
20      False    True  False  False   91738.0              6.8        No
21       True   False  False  False   98273.0              7.1        No
22       True   False  False  False  101302.0              7.9        No
23       True   False  False  False  113812.0              8.2       Yes
24      False   False   True  False  109431.0              8.7        No
25       True   False  False  False  105582.0              9.0       Yes
26      False   False   True  False  116969.0              9.5        No
27      False   False  False   True  112635.0              9.6       Yes
28      False   False  False   True  122391.0             10.3        No
29      False    True  False  False  121872.0             10.5       Yes

# <h3> Let's do it with Scikit-Learn </h3>
Also Restart your kernel if you are using same notebook

In [33]:
# Lets first perform label encoding
# Labelencoding will be performed on Purchased column as it has only two unique value in it.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_1['Purchased'] = le.fit_transform(df_1['Purchased'])
df_1.head(40)

    Australia  Canada  Dubai    USA    Salary  YearsExperience  Purchased
0       False   False   True  False   39343.0              1.1          0
1       False    True  False  False   46205.0              1.3          1
2       False    True  False  False   37731.0              1.5          0
3       False    True  False  False   43525.0              2.0          0
4       False   False  False   True   39891.0              2.2          0
5       False   False   True  False   56642.0              2.9          0
6       False    True  False  False   60150.0              3.0          1
7        True   False  False  False   54445.0              3.2          0
8       False   False   True  False   64445.0              3.2          1
9       False   False   True  False   57189.0              3.7          0
10      False   False   True  False   63218.0              3.9          1
11      False   False  False   True   55794.0              4.0          0
12      False   False   True  False   56957.0              4.0          1
13      False    True  False  False   57081.0              4.1          0
14       True   False  False  False   61111.0              4.5          0
15      False   False  False   True   67938.0              4.9          0
16      False   False  False   True   66029.0              5.1          0
17      False    True  False  False   83088.0              5.3          0
18       True   False  False  False   81363.0              5.9          1
19      False    True  False  False   93940.0              6.0          0
20      False    True  False  False   91738.0              6.8          0
21       True   False  False  False   98273.0              7.1          0
22       True   False  False  False  101302.0              7.9          0
23       True   False  False  False  113812.0              8.2          1
24      False   False   True  False  109431.0              8.7          0
25       True   False  False  False  105582.0              9.0          1
26      False   False   True  False  116969.0              9.5          0
27      False   False  False   True  112635.0              9.6          1
28      False   False  False   True  122391.0             10.3          0
29      False    True  False  False  121872.0             10.5          1

In [50]:
# Lets perform one-hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
df = pd.DataFrame(ct.fit_transform(dataset))

In [51]:
df.columns = ['Australia','Canada','Dubai','USA','Salary', 'YearsExperience', 'Purchased']
df.head(10)

  Australia Canada Dubai  USA   Salary YearsExperience Purchased
0       0.0    0.0   1.0  0.0  39343.0             1.1        No
1       0.0    1.0   0.0  0.0  46205.0             1.3       Yes
2       0.0    1.0   0.0  0.0  37731.0             1.5        No
3       0.0    1.0   0.0  0.0  43525.0             2.0        No
4       0.0    0.0   0.0  1.0  39891.0             2.2        No
5       0.0    0.0   1.0  0.0  56642.0             2.9        No
6       0.0    1.0   0.0  0.0  60150.0             3.0       Yes
7       1.0    0.0   0.0  0.0  54445.0             3.2        No
8       0.0    0.0   1.0  0.0  64445.0             3.2       Yes
9       0.0    0.0   1.0  0.0  57189.0             3.7        No

In [52]:
#You can find the sorted list of column names of encoding variable by this method.
print(sorted(list(dataset['country'].unique())))
#To find the name of all the columns of dataset.
dataset.columns

['Australia', 'Canada', 'Dubai', 'USA']

Index(['country', 'Salary', 'YearsExperience', 'Purchased'], dtype='object')